# File handling - Control how files are renamed and processed
rename_with_timestamp: true
preserve_original_filename: true
filename_template: "{original}_{timestamp}"
timestamp_format: "%Y%m%d_%H%M%S"
