# File handling - Control how files are renamed and processed
rename_with_timestamp: false
preserve_original_filename: true
filename_template: "{original}_{timestamp}"
timestamp_format: "%Y%m%d_%H%M%S"

# Media transfer settings - Control which files are transferred
media_only_transfer: true
preserve_folder_structure: true
media_extensions: .mp4,.mov,.mxf,.avi,.braw,.r3d,.wav,.aif,.aiff,.crm,.arw,.raw,.cr2,.jpg,.jpeg,.png,.tiff,.tif,.dpx,.exr,.xml,.cdl,.cube

# Directory structure settings - Control how files are organized
create_date_folders: true
date_folder_format: "%Y/%m/%d"
create_device_folders: false
device_folder_template: "{device_name}"

# Proxy generation settings - Control video proxy creation
generate_proxies: false
proxy_subfolder: proxies
include_proxy_watermark: true
proxy_watermark_path: assets/adobe_proxy_logo.png
